### ISSUE TITLE
Volume size displayed in pod is wrong

### ISSUE THREAD

**Issue by couloum** [kadalu/kadalu#300]
Hi,

We juste deployed kadalu to give it a try. We currently use heketti and are following this project very attentively.

When we deployed kadalu on a test cluster, we observed a strange behavior and we don't know if it's normal or not.

We created a PVC of 2GB. When we mount it on pods, and do a `df -h` on them, we don't see 2GB size for the mounted volume, but 477GB (size of the underlying disks).

```
$ kubectl get pvc
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
gluster-vol-sample   Bound    pvc-18a95c6e-f384-46fc-9335-ed32255ddad1   2Gi        RWX            kadalu.replica3   29h

$ kubectl get pvc -o yaml gluster-vol-sample
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"gluster-vol-sample","nam
espace":"default"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"2Gi"}},"storageClassNa
me":"kadalu.replica3"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kadalu
  creationTimestamp: "2020-09-08T09:20:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: gluster-vol-sample
  namespace: default
  resourceVersion: "27178013"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/gluster-vol-sample
  uid: 18a95c6e-f384-46fc-9335-ed32255ddad1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: kadalu.replica3
  volumeMode: Filesystem
  volumeName: pvc-18a95c6e-f384-46fc-9335-ed32255ddad1
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  phase: Bound

$  kubectl get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   3/3     3            3           29h

$ kubectl get deploy nginx -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"nginx"},"name":"nginx
","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{"rollingUpdate":
{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"
containers":[{"envFrom":[{"configMapRef":{"name":"nginx"}}],"image":"nginx","imagePullPolicy":"IfNotPresent","name":"
nginx","volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"nginx-vol"}]}],"restartPolicy":"Always","volumes"
:[{"name":"nginx-vol","persistentVolumeClaim":{"claimName":"gluster-vol-sample"}}]}}}}
  creationTimestamp: "2020-09-08T09:21:00Z"
  generation: 3
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "27233782"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nginx
  uid: 9878e755-99e6-4a9e-9e91-b6a528699997
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2020-09-08T14:39:29Z"
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-vol
        persistentVolumeClaim:
          claimName: gluster-vol-sample
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-09-08T14:37:03Z"
    lastUpdateTime: "2020-09-08T14:37:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-08T09:21:00Z"
    lastUpdateTime: "2020-09-08T14:39:32Z"
    message: ReplicaSet "nginx-7dc9d49448" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3

$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-7dc9d49448-b49m9   1/1     Running   0          23h
nginx-7dc9d49448-dv9k2   1/1     Running   0          23h
nginx-7dc9d49448-xxc86   1/1     Running   0          23h

$ kubectl exec -ti nginx-7dc9d49448-dv9k2 df -- -h /usr/share/nginx/html
Filesystem                                Size  Used Avail Use% Mounted on
/kadalu/volfiles/storage-pool.client.vol  477G  8.2G  469G   2% /usr/share/nginx/html
```

Also, as a consequence, we can store more than 2GB in this volume.

Is this normal?

Thanks

**Comment by amarts** [comment]
Interesting. This looks very much like the host volume mount.

Kadalu uses subdir and sets Quota on it (xfs quota at present) and then uses the storage. You used path or Device for the storage pool?

**Comment by amarts** [comment]
> Is this normal?

Surely not!

**Comment by aravindavk** [comment]
How Kadalu Storage is configured? Using `path` or using `device`. My suspect is XFS Quota is not enabled and directory is provided while creating Kadalu Storage pool. Please confirm.

**Comment by couloum** [comment]
We used `device`. We created the storage-pool using this command:

```
kubectl kadalu storage-add storage-pool --type=Replica3 --device kubnode01:/dev/sdc --device kubnode02:/dev/sdc --device kubnode03:/dev/sdc
```

and kadalu was installed using this command:

```
pip3 install kubectl-kadalu
kubectl kadalu install --version 0.7.0 --type kubernetes
```

Would that confirm your hint?

Thanks

**Comment by aravindavk** [comment]
> Would that confirm your hint?

My suspect was wrong, the steps used were proper. But looks like backend Quota set is failing. Any errors/traces in Server pod logs?

Also what is the Host operating system used?

**Comment by couloum** [comment]
It seems there is a DNS resolution issue in `server-storage-pool-0-0/shd`:

```
[2020-09-08 09:19:59.776476] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-storage-pool-replicate-0-client-0: DNS resolution failed on host server-storage-pool-0-0.storage-pool
The message "E [MSGID: 101075] [common-utils.c:503:gf_resolve_ip6] 0-resolver: getaddrinfo failed (family:0) (Name or service not known)" repeated 27 times between [2020-09-08 09:19:32.732870] and [2020
-09-08 09:19:59.776470]
[2020-09-08 09:19:59.784904] I [MSGID: 114057] [client-handshake.c:1372:select_server_supported_programs] 0-storage-pool-replicate-0-client-1: Using Program GlusterFS 4.x v1, Num (1298437), Version (400)
[2020-09-08 09:19:59.785067] W [dict.c:998:str_to_data] (-->/usr/lib64/glusterfs/7.5/xlator/protocol/client.so(+0x37860) [0x7fbcb8ea2860] -->/lib64/libglusterfs.so.0(dict_set_str+0x1b) [0x7fbcbd61878b] -->/lib64/libglusterfs.so.0(str_to_data+0x60) [0x7fbcbd615170] ) 0-dict: value is NULL [Invalid argument]
[2020-09-08 09:19:59.785088] I [MSGID: 114006] [client-handshake.c:1235:client_setvolume] 0-storage-pool-replicate-0-client-1: failed to set process-name in handshake msg
[2020-09-08 09:19:59.787230] E [MSGID: 101075] [common-utils.c:503:gf_resolve_ip6] 0-resolver: getaddrinfo failed (family:0) (Name or service not known)
[2020-09-08 09:19:59.787256] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-storage-pool-replicate-0-client-2: DNS resolution failed on host server-storage-pool-2-0.storage-pool
[2020-09-08 09:19:59.789444] I [MSGID: 114046] [client-handshake.c:1103:client_setvolume_cbk] 0-storage-pool-replicate-0-client-1: Connected to storage-pool-replicate-0-client-1, attached to remote volume '/bricks/storage-pool/data/brick'.
[2020-09-08 09:19:59.789484] I [MSGID: 108005] [afr-common.c:5280:__afr_handle_child_up_event] 0-storage-pool-replicate-0: Subvolume 'storage-pool-replicate-0-client-1' came back up; going online.
[2020-09-08 09:20:02.783958] I [MSGID: 114057] [client-handshake.c:1372:select_server_supported_programs] 0-storage-pool-replicate-0-client-0: Using Program GlusterFS 4.x v1, Num (1298437), Version (400)
[2020-09-08 09:20:02.784024] W [dict.c:998:str_to_data] (-->/usr/lib64/glusterfs/7.5/xlator/protocol/client.so(+0x37860) [0x7fbcb8ea2860] -->/lib64/libglusterfs.so.0(dict_set_str+0x1b) [0x7fbcbd61878b] -->/lib64/libglusterfs.so.0(str_to_data+0x60) [0x7fbcbd615170] ) 0-dict: value is NULL [Invalid argument]
[2020-09-08 09:20:02.784036] I [MSGID: 114006] [client-handshake.c:1235:client_setvolume] 0-storage-pool-replicate-0-client-0: failed to set process-name in handshake msg
[2020-09-08 09:20:02.784418] I [MSGID: 114046] [client-handshake.c:1103:client_setvolume_cbk] 0-storage-pool-replicate-0-client-0: Connected to storage-pool-replicate-0-client-0, attached to remote volume '/bricks/storage-pool/data/brick'.
[2020-09-08 09:20:02.792713] I [MSGID: 114057] [client-handshake.c:1372:select_server_supported_programs] 0-storage-pool-replicate-0-client-2: Using Program GlusterFS 4.x v1, Num (1298437), Version (400)
[2020-09-08 09:20:02.792784] W [dict.c:998:str_to_data] (-->/usr/lib64/glusterfs/7.5/xlator/protocol/client.so(+0x37860) [0x7fbcb8ea2860] -->/lib64/libglusterfs.so.0(dict_set_str+0x1b) [0x7fbcbd61878b] -->/lib64/libglusterfs.so.0(str_to_data+0x60) [0x7fbcbd615170] ) 0-dict: value is NULL [Invalid argument]
[2020-09-08 09:20:02.792793] I [MSGID: 114006] [client-handshake.c:1235:client_setvolume] 0-storage-pool-replicate-0-client-2: failed to set process-name in handshake msg
[2020-09-08 09:20:02.795038] I [MSGID: 114046] [client-handshake.c:1103:client_setvolume_cbk] 0-storage-pool-replicate-0-client-2: Connected to storage-pool-replicate-0-client-2, attached to remote volume '/bricks/storage-pool/data/brick'.
```

I don't see other error log

We use Ubuntu 20.04:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

$ uname -a
Linux myhostname 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Here are all the pods running:

```
$ kubectl -n kadalu get pods
NAME                        READY   STATUS    RESTARTS   AGE
csi-nodeplugin-frx6w        3/3     Running   0          7d5h
csi-nodeplugin-rv69z        3/3     Running   0          7d5h
csi-nodeplugin-thm8t        3/3     Running   0          7d5h
csi-provisioner-0           4/4     Running   0          7d5h
operator-7d685cf97d-rdbdk   1/1     Running   0          7d5h
server-storage-pool-0-0     3/3     Running   0          7d5h
server-storage-pool-1-0     3/3     Running   0          7d5h
server-storage-pool-2-0     3/3     Running   0          7d5h
```

**Comment by couloum** [comment]
Hi,

We have upgraded Kadalu to v0.7.1 but still have the bug. Do you have any idea where it can come from? Do you want me to run some debugging commands on servers?

Thanks

**Comment by al45tair** [comment]
Have you got XFS project quotas turned on for the underlying storage volume? There's a mount option you need to use to enable it; see [xfs(5)](https://www.man7.org/linux/man-pages/man5/xfs.5.html).

**Comment by aravindavk** [comment]
> Have you got XFS project quotas turned on for the underlying storage volume? There's a mount option you need to use to enable it; see xfs(5).

When raw device is provided while adding Kadalu Storage, then xfs quota will be set by Kadalu server pod itself.

https://github.com/kadalu/kadalu/blob/devel/server/glusterfsd.py#L117

**Comment by al45tair** [comment]
@aravindavk That's true, but if this is an external Gluster, that won't be the case.

**Comment by couloum** [comment]
Yes, quota seems to be enabled as you can see:
```
kubenode>~$ mount | grep gluster
/dev/mapper/sdc_crypt on /var/lib/kubelet/pods/a4de8387-7cab-4b69-8120-cc931bdd5807/volumes/kubernetes.io~empty-dir/glusterfsd-mountdir/data type xfs (rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,prjquota)
/kadalu/volfiles/storage-pool.client.vol on /var/lib/kubelet/pods/7ab81b60-7889-4eb8-8897-65af325dd301/volumes/kubernetes.io~csi/pvc-e6edf49f-9864-4a7b-a09e-1e414994f8be/mount type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
```

```
kubenode>~$ lsblk
NAME                MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
(...)
sdc                   8:32   0   477G  0 disk
└─sdc_crypt         253:3    0 476.9G  0 crypt /var/lib/kubelet/pods/a4de8387-7cab-4b69-8120-cc931bdd5807/volumes/kubernetes.io~empty-dir/glusterfsd-mountdir/data

kubenode>~$ df -h
Filesystem                               Type            Size  Used Avail Use% Mounted on
(...)
/dev/mapper/sdc_crypt                    xfs             477G  8.7G  469G   2% /var/lib/kubelet/pods/a4de8387-7cab-4b69-8120-cc931bdd5807/volumes/kubernetes.io~empty-dir/glusterfsd-mountdir/data
/kadalu/volfiles/storage-pool.client.vol fuse.glusterfs  477G   14G  464G   3% /var/lib/kubelet/pods/7ab81b60-7889-4eb8-8897-65af325dd301/volumes/kubernetes.io~csi/pvc-e6edf49f-9864-4a7b-a09e-1e414994f8be/mount
```

**Comment by amarts** [comment]
@couloum Sorry we took time to get back on this. We did multiple changes in our `0.7.x` series, and have seen most of the issues are resolved in `0.7.6` release. Let us know if you see similar issues in later releases. Thanks.

**Comment by couloum** [comment]
Thanks @amarts . We'll do the upgrade to 0.7.6 and update this issue.

**Comment by couloum** [comment]
Hi,

We performed the upgrade to v0.7.6, but we still have the same behavior.

```
# kubectl kadalu version
kubectl-kadalu 0.7.6

# kubectl -n kadalu get ds,deploy -o wide
NAME                                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE    CONTAINERS                                                   IMAGES                                                                                             SELECTOR
daemonset.apps/csi-nodeplugin          3         3         3       3            3           <none>          135d   csi-node-driver-registrar,kadalu-nodeplugin,kadalu-logging   quay.io/k8scsi/csi-node-driver-registrar:v1.0.1,docker.io/kadalu/kadalu-csi:0.7.0,busybox          app.kubernetes.io/component=csi-driver,app.kubernetes.io/name=csi-nodeplugin,app.kubernetes.io/part-of=kadalu
daemonset.apps/kadalu-csi-nodeplugin   3         3         3       3            3           <none>          85d    csi-node-driver-registrar,kadalu-nodeplugin,kadalu-logging   docker.io/raspbernetes/csi-node-driver-registrar:2.0.1,docker.io/kadalu/kadalu-csi:0.7.6,busybox   app.kubernetes.io/component=csi-driver,app.kubernetes.io/name=kadalu-csi-nodeplugin,app.kubernetes.io/part-of=kadalu

NAME                       READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS        IMAGES                                   SELECTOR
deployment.apps/operator   1/1     1            1           135d   kadalu-operator   docker.io/kadalu/kadalu-operator:0.7.6   name=kadalu
```

Total size is still wrong:

```
# kubectl -n hello-world get pvc,pv
NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
persistentvolumeclaim/mysql   Bound    pvc-eee99e77-9244-4f24-971b-7c07cdaf369a   1Gi        RWO            kadalu.replica3   3m9s

NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                       STORAGECLASS      REASON   AGE
persistentvolume/pvc-eee99e77-9244-4f24-971b-7c07cdaf369a   1Gi        RWO            Delete           Bound    hello-world/mysql                           kadalu.replica3            3m4s

# kubectl -n hello-world exec -ti mysql-6fcf9765f-n24mf -- df -h /var/lib/mysql
Filesystem                                Size  Used Avail Use% Mounted on
/kadalu/volfiles/storage-pool.client.vol  477G  8.6G  469G   2% /var/lib/mysql
```

And we can exceed quota of 1GB (as we're consuming 8.6GB on a 1GB volume).

Here are some logs:
```
# kubectl -n kadalu logs --tail 10 csi-provisioner-0 kadalu-logging
[2021-01-22 10:40:37.252835] I [fuse-bridge.c:5162:fuse_init] 0-glusterfs-fuse: FUSE inited with protocol versions: glusterfs 7.24 kernel 7.31
[2021-01-22 10:40:37.252846] I [fuse-bridge.c:5777:fuse_graph_sync] 0-fuse: switched to graph 0
[2021-01-22 10:40:37.323252] W [MSGID: 114031] [client-rpc-fops_v2.c:516:client4_0_rmdir_cbk] 0-storage-pool-replicate-0-client-0: remote operation failed [Directory not empty]
[2021-01-22 10:40:37.323655] W [MSGID: 114031] [client-rpc-fops_v2.c:516:client4_0_rmdir_cbk] 0-storage-pool-replicate-0-client-1: remote operation failed [Directory not empty]
[2021-01-22 10:40:37.325626] W [MSGID: 114031] [client-rpc-fops_v2.c:516:client4_0_rmdir_cbk] 0-storage-pool-replicate-0-client-0: remote operation failed [Directory not empty]
[2021-01-22 10:40:37.326186] W [MSGID: 114031] [client-rpc-fops_v2.c:516:client4_0_rmdir_cbk] 0-storage-pool-replicate-0-client-1: remote operation failed [Directory not empty]
[2021-01-22 10:40:37.327696] W [MSGID: 114031] [client-rpc-fops_v2.c:516:client4_0_rmdir_cbk] 0-storage-pool-replicate-0-client-0: remote operation failed [Directory not empty]
[2021-01-22 10:40:37.327989] W [MSGID: 114031] [client-rpc-fops_v2.c:516:client4_0_rmdir_cbk] 0-storage-pool-replicate-0-client-1: remote operation failed [Directory not empty]
[2021-01-22 10:40:37.329649] W [MSGID: 114031] [client-rpc-fops_v2.c:516:client4_0_rmdir_cbk] 0-storage-pool-replicate-0-client-0: remote operation failed [Directory not empty]
[2021-01-22 10:40:37.329990] W [MSGID: 114031] [client-rpc-fops_v2.c:516:client4_0_rmdir_cbk] 0-storage-pool-replicate-0-client-1: remote operation failed [Directory not empty]

# kubectl -n kadalu logs --tail 10 csi-nodeplugin-4dhsd kadalu-logging
[2021-01-22 10:41:33.091617] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (1736526b-b995-4381-8c54-8057d5485034) remote_fd is -1. EBADFD [File descriptor in bad state]
[2021-01-22 10:42:34.046361] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (31ddb365-b314-4883-b7de-a23a816c2eeb) remote_fd is -1. EBADFD [File descriptor in bad state]
[2021-01-22 10:43:35.095274] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (000036b8-89eb-4a3f-8842-09b4be8b3eaf) remote_fd is -1. EBADFD [File descriptor in bad state]
[2021-01-22 10:44:36.064037] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (3190bcc7-d0f3-4818-a8f3-7dffcb6ae9d6) remote_fd is -1. EBADFD [File descriptor in bad state]
[2021-01-22 10:45:37.074775] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (46338fb9-56f2-4e5b-ad11-362187d912ef) remote_fd is -1. EBADFD [File descriptor in bad state]
[2021-01-22 10:46:38.109366] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (e8b808d9-a19b-475f-a809-7b8112a9476d) remote_fd is -1. EBADFD [File descriptor in bad state]
[2021-01-22 10:47:39.049583] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (768ae2f6-0810-4915-8bfd-099dd991eb5a) remote_fd is -1. EBADFD [File descriptor in bad state]
[2021-01-22 10:48:40.090109] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (1c975a9c-7f72-4da7-a8a1-541a0cf77008) remote_fd is -1. EBADFD [File descriptor in bad state]
[2021-01-22 10:49:41.034353] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (bdee84b0-5906-4d26-b1a9-f06bb05460fe) remote_fd is -1. EBADFD [File descriptor in bad state]
[2021-01-22 10:50:42.105668] W [MSGID: 114061] [client-common.c:2625:client_pre_flush_v2] 0-storage-pool-replicate-0-client-2:  (cd7d9728-f7f8-4b14-9815-7533d0d86bbb) remote_fd is -1. EBADFD [File descriptor in bad state]

# kubectl -n kadalu logs --tail 10 kadalu-csi-nodeplugin-55fgb  kadalu-logging
[2021-01-22 10:50:17.826550] I [MSGID: 114057] [client-handshake.c:1373:select_server_supported_programs] 0-storage-pool-replicate-0-client-0: Using Program GlusterFS 4.x v1, Num (1298437), Version (400)
[2021-01-22 10:50:17.826585] I [MSGID: 114046] [client-handshake.c:1104:client_setvolume_cbk] 0-storage-pool-replicate-0-client-2: Connected to storage-pool-replicate-0-client-2, attached to remote volume '/bricks/storage-pool/data/brick'.
[2021-01-22 10:50:17.826598] I [MSGID: 108005] [afr-common.c:5278:__afr_handle_child_up_event] 0-storage-pool-replicate-0: Subvolume 'storage-pool-replicate-0-client-2' came back up; going online.
[2021-01-22 10:50:17.826878] I [MSGID: 114046] [client-handshake.c:1104:client_setvolume_cbk] 0-storage-pool-replicate-0-client-1: Connected to storage-pool-replicate-0-client-1, attached to remote volume '/bricks/storage-pool/data/brick'.
[2021-01-22 10:50:17.826889] I [MSGID: 108002] [afr-common.c:5647:afr_notify] 0-storage-pool-replicate-0: Client-quorum is met
[2021-01-22 10:50:17.827170] I [MSGID: 114046] [client-handshake.c:1104:client_setvolume_cbk] 0-storage-pool-replicate-0-client-0: Connected to storage-pool-replicate-0-client-0, attached to remote volume '/bricks/storage-pool/data/brick'.
[2021-01-22 10:50:17.827698] I [fuse-bridge.c:5162:fuse_init] 0-glusterfs-fuse: FUSE inited with protocol versions: glusterfs 7.24 kernel 7.31
[2021-01-22 10:50:17.827708] I [fuse-bridge.c:5777:fuse_graph_sync] 0-fuse: switched to graph 0
[2021-01-22 10:50:17.825750] I [MSGID: 114020] [client.c:2434:notify] 0-storage-pool-replicate-0-client-0: parent translators are ready, attempting connect on transport
[2021-01-22 10:50:17.825751] I [MSGID: 114020] [client.c:2434:notify] 0-storage-pool-replicate-0-client-1: parent translators are ready, attempting connect on transport
```

Let me know if you need more logs are if you need me to perform some commands.

Regards

**Comment by couloum** [comment]
Hi,

We performed an upgrade to v0.8.2 and now the sizing is correct!

```
# kubectl -n filter get pvc
--
NAME                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
gni-redis               Bound    pvc-73ae154e-99e3-4c10-8646-d2628f1b862d   3Gi        RWO            kadalu.replica3   3d5h

# kubectl -n filter exec -it gni-redis-68c6d4d85b-thdv9 -- sh
Defaulting container name to gni-redis.
Use 'kubectl describe pod/gni-redis-68c6d4d85b-thdv9 -n filter' to see all of the containers in this pod.
/data # df -h /data
Filesystem                Size      Used Available Use% Mounted on
/kadalu/volfiles/storage-pool.client.vol
3.0G         0      3.0G   0% /data
```

I will close this issue.

Thanks for the quality of the work on this project!
