### ISSUE TITLE
kadalu-nodeplugin: Exception calling application: [Errno 2] No such file or directory: '/kadalu/templates/External.client.vol.j2'

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#399]
Hi,

with 0.7.5 I now get new exceptions. Here is one from the kadalu-nodeplugin container (using an external Gluster Storage):

```
[2020-12-24 06:49:23,494] DEBUG [nodeserver - 41:NodePublishVolume] - Received the mount request	 volume=pvc-6fed14c5-14a1-49f4-ae66-1be9e82dedf1 voltype=unknown hostvol=ext-pool pvpath=subvol/57/d1/pvc-6fed14c5-14a1-49f4-ae66-1be9e82dedf1 pvtype=subvol
[2020-12-24 06:49:23,509] ERROR [_server - 445:_call_behavior] - Exception calling application: [Errno 2] No such file or directory: '/kadalu/templates/External.client.vol.j2'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 72, in NodePublishVolume
    mount_glusterfs(volume, mntdir)
  File "/kadalu/volumeutils.py", line 611, in mount_glusterfs
    generate_client_volfile(volume['name'])
  File "/kadalu/volumeutils.py", line 568, in generate_client_volfile
    with open(template_file_path) as template_file:
FileNotFoundError: [Errno 2] No such file or directory: '/kadalu/templates/External.client.vol.j2'
```

Cheers,

floek

**Comment by amarts** [comment]
this is interesting, because External clients should use mount from glusterd (and not from template). Will check this. It should never get to `generate_client_volfile` instead should be doing `mount_glusterfs_with_host`.

Is the storage config valid?

**Comment by floek** [comment]
Sorry for opening two new issues, after closing two ;-).

I think the storage config is valid, kadalu data is created on the volume (info, stat.db, subvol) and I haven't changed the config in my ansible playbook.

Tell me, if I could help debugging.

**Comment by floek** [comment]
Oh, I just saw the kadalu executable is still 0.7.4. I will upgrade and try again.

**Comment by floek** [comment]
Okay, now I'm on 0.7.5 same exception.

**Comment by amarts** [comment]
While I was not able to reproduce this, I ran few tests with 0.7.6 version, and things seems to be fine. Please check if its all fine now.

**Comment by floek** [comment]
It still exists in 0.7.6:
```console
2021-01-19 07:13:50,620] ERROR [_server - 445:_call_behavior] - Exception calling application: [Errno 2] No such file or directory: '/kadalu/templates/External.client.vol.j2'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 72, in NodePublishVolume
    mount_glusterfs(volume, mntdir)
  File "/kadalu/volumeutils.py", line 803, in mount_glusterfs
    generate_client_volfile(volume['name'])
  File "/kadalu/volumeutils.py", line 760, in generate_client_volfile
    with open(template_file_path) as template_file:
FileNotFoundError: [Errno 2] No such file or directory: '/kadalu/templates/External.client.vol.j2'
```

**Comment by amarts** [comment]
Ok, I guess, I found the issue.

This means, the request to get PVC doesn't include a storage class which has `hostvol_type: External` set.

How is the external storage config set?

**Comment by amarts** [comment]
Please add `storageClassName` option to PVC request if its not already added.

**Comment by floek** [comment]
Hi,

thanks for analysing this. You are perfectly right. I just set my `storageClassName` to `kadalu` instead of the right external storageClassName. Maybe the error could be caught and given a nicer error message. But that's just a nice to have.

The issue can be closed.

Cheers,

floek

**Comment by floek** [comment]
One follow up problem of this issue is: I've now problems to delete the pv and pvc. Maybe some error handling would help.

**Comment by amarts** [comment]
Sure, will not close the issue till those minor hiccups are fixed.

**Comment by fastlorenzo** [comment]
This issue is still happening with latest devel version:
```
[2022-01-15 23:11:52,128] INFO [kadalulib - 405:monitor_proc] - Restarted Process        name=csi
Traceback (most recent call last):
  File "/kadalu/main.py", line 86, in <module>
    main()
  File "/kadalu/main.py", line 66, in main
    mount_storage()
  File "/kadalu/main.py", line 39, in mount_storage
    mount_glusterfs(volume, mntdir)
  File "/kadalu/volumeutils.py", line 1128, in mount_glusterfs
    generate_client_volfile(volname)
  File "/kadalu/volumeutils.py", line 945, in generate_client_volfile
    with open(template_file_path) as template_file:
FileNotFoundError: [Errno 2] No such file or directory: '/kadalu/templates/External.client.vol.j2'
```

Storage config:
```yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: data
  namespace: kadalu
spec:
  type: External
  kadalu_format: native
  details:
    gluster_hosts: ["172.17.0.1"]
    gluster_volname: data
    gluster_options: log-level=DEBUG
```

**Comment by fastlorenzo** [comment]
A bit of investigation shows that this is only happening when using `native` mode. As can be seen in the following, if `non-native` is used, `mount_glusterfs` is not called due to the `continue`:

https://github.com/kadalu/kadalu/blob/26562e98217d8fc495dd341b6dd4b776b912469a/csi/main.py#L30-L42

Question: should `get_pv_hosting_volumes` also return `External` volumes? If that function doesn't, this could fix the issue, if it should, maybe there should be a check on line 39 to use the correct mount method (`mount_glusterfs_with_host` if an `External` volume).

**Comment by fastlorenzo** [comment]
Digging a bit deeper, I see this is handled in `mount_glusterfs`:
https://github.com/kadalu/kadalu/blob/26562e98217d8fc495dd341b6dd4b776b912469a/csi/volumeutils.py#L1180-L1188

The issue is that in that function, the code below is not working if this is an `External` volume. Maybe it should be put under an `if volume['type'] != 'External':`?
https://github.com/kadalu/kadalu/blob/26562e98217d8fc495dd341b6dd4b776b912469a/csi/volumeutils.py#L1128-L1176

**Comment by fastlorenzo** [comment]
ok, found a fix and added it to PR #745 => tested working on my setup
