### ISSUE TITLE
Disk usage miscalculated / quota exceeded

### ISSUE THREAD

**Issue by benedekl** [kadalu/kadalu#577]
Dear guys,

First, thank you for this awesome storage solution.

I have made a 3 node (Replica3) setup on Kubernetes. The bricks are on the master nodes. I'm using `docker.io/kadalu/kadalu-operator:devel` image as operator and tweaked the servers to tolerate `node-role.kubernetes.io/master` taints.

```yaml
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-1
  namespace: kadalu
spec:
  storage:
    - device: /dev/vg0/gluster
      node: master-00
    - device: /dev/vg0/gluster
      node: master-01
    - device: /dev/vg0/gluster
      node: master-02
  type: Replica3
```

```
$ kubectl get nodes
NAME        STATUS   ROLES                  AGE   VERSION
master-00   Ready    control-plane,master   74d   v1.21.0
master-01   Ready    control-plane,master   74d   v1.21.0
master-02   Ready    control-plane,master   74d   v1.21.0
worker-00   Ready    <none>                 17d   v1.21.0
```

```
$ kubectl get pods -n kadalu -o wide
NAME                          READY   STATUS    RESTARTS   AGE   IP             NODE        NOMINATED NODE   READINESS GATES
kadalu-csi-nodeplugin-tbg6v   3/3     Running   0          25h   10.112.4.186   worker-00   <none>           <none>
kadalu-csi-provisioner-0      5/5     Running   0          25h   10.112.4.187   worker-00   <none>           <none>
operator-cb9d78479-gc9fj      1/1     Running   0          25h   10.112.4.189   worker-00   <none>           <none>
server-storage-pool-1-0-0     1/1     Running   0          25h   10.112.0.74    master-00   <none>           <none>
server-storage-pool-1-1-0     1/1     Running   0          25h   10.112.1.46    master-01   <none>           <none>
server-storage-pool-1-2-0     1/1     Running   0          25h   10.112.2.45    master-02   <none>           <none>
```

I tried to create a simple webserver deployment with PVC and everything seems fine. The PV has the correct size. I can exec into the pod and can create a 200M file on a 200M PV. After removing the file the used space goes back to 0.

Now I try to use a similar 1G PVC for Prometheus storage. Prometheus starts fine and collects data as well. Soon Prometheus stops with disk quote exceeded message. `df` shows 0% free space, manually creating a file also fails. `du` counts only 20-60M file usage. When I remove all these files with `rm`, `df` still shows 0% free space. I can't do anything to recover the allocated space.

```
kadalu:storage-pool-1  1048580   1048580         0 100% /prometheus

```

The bricks have plenty of free space (20G):
```
/dev/mapper/vg0-gluster   20G  240M   20G   2% /bricks/storage-pool-1/data
```
I can see in the logs these messages:
```
[2021-06-15 13:51:53.860001 +0000] W [MSGID: 114031] [client-rpc-fops_v2.c:842:client4_0_setxattr_cbk] 0-storage-pool-1-client-0: remote operation failed. [{errno=1}, {error=Operation not permitted}] 
The message "W [MSGID: 114031] [client-rpc-fops_v2.c:842:client4_0_setxattr_cbk] 0-storage-pool-1-client-0: remote operation failed. [{errno=1}, {error=Operation not permitted}]" repeated 4 times between [2021-06-15 13:51:53.860001 +0000] and [2021-06-15 13:51:53.897337 +0000]
[2021-06-15 13:51:53.906521 +0000] I [MSGID: 108026] [afr-self-heal-metadata.c:51:__afr_selfheal_metadata_do] 0-storage-pool-1-replica-0: performing metadata selfheal on e01b6ba2-efcb-4ba3-ac56-9fde6dd69da1 
[2021-06-15 13:51:53.909480 +0000] W [MSGID: 114031] [client-rpc-fops_v2.c:842:client4_0_setxattr_cbk] 0-storage-pool-1-client-0: remote operation failed. [{errno=1}, {error=Operation not permitted}] 
[2021-06-15 13:51:53.914247 +0000] I [MSGID: 108026] [afr-self-heal-common.c:1732:afr_log_selfheal] 0-storage-pool-1-replica-0: Completed metadata selfheal on e01b6ba2-efcb-4ba3-ac56-9fde6dd69da1. sources=[1] 2  sinks= 
```
```
[2021-06-15 14:01:41.181531 +0000] W [simple-quota.c:896:sq_setxattr] 0-storage-pool-1-quota: request sent on non-namespace inode (trusted.gfs.squota.limit)
[2021-06-15 14:01:41.181563 +0000] I [MSGID: 115060] [server-rpc-fops.c:932:_gf_server_log_setxattr_failure] 0-storage-pool-1-server: 11519886: SETXATTR /subvol/aa/00/pvc-32448cd0-cd12-404a-8a2c-674d03f4c0e4 (f16bc78b-edf4-494e-b043-1a0642fb01e4) ==> trusted.glusterfs.dht, client: CTX_ID:90b5ae83-7b1b-49f5-8b6e-cb505ceb37ed-GRAPH_ID:0-PID:10-HOST:server-storage-pool-1-0-0-PC_NAME:storage-pool-1-client-0-RECON_NO:-0, error-xlator: storage-pool-1-quota 
[2021-06-15 14:01:41.181587 +0000] I [MSGID: 115060] [server-rpc-fops.c:932:_gf_server_log_setxattr_failure] 0-storage-pool-1-server: 11519886: SETXATTR /subvol/aa/00/pvc-32448cd0-cd12-404a-8a2c-674d03f4c0e4 (f16bc78b-edf4-494e-b043-1a0642fb01e4) ==> trusted.gfs.squota.limit, client: CTX_ID:90b5ae83-7b1b-49f5-8b6e-cb505ceb37ed-GRAPH_ID:0-PID:10-HOST:server-storage-pool-1-0-0-PC_NAME:storage-pool-1-client-0-RECON_NO:-0, error-xlator: storage-pool-1-quota 
[2021-06-15 14:01:41.181605 +0000] I [MSGID: 115060] [server-rpc-fops.c:932:_gf_server_log_setxattr_failure] 0-storage-pool-1-server: 11519886: SETXATTR /subvol/aa/00/pvc-32448cd0-cd12-404a-8a2c-674d03f4c0e4 (f16bc78b-edf4-494e-b043-1a0642fb01e4) ==> trusted.glusterfs.namespace, client: CTX_ID:90b5ae83-7b1b-49f5-8b6e-cb505ceb37ed-GRAPH_ID:0-PID:10-HOST:server-storage-pool-1-0-0-PC_NAME:storage-pool-1-client-0-RECON_NO:-0, error-xlator: storage-pool-1-quota 
[2021-06-15 14:01:41.181622 +0000] I [MSGID: 115060] [server-rpc-fops.c:932:_gf_server_log_setxattr_failure] 0-storage-pool-1-server: 11519886: SETXATTR /subvol/aa/00/pvc-32448cd0-cd12-404a-8a2c-674d03f4c0e4 (f16bc78b-edf4-494e-b043-1a0642fb01e4) ==> trusted.glusterfs.mdata, client: CTX_ID:90b5ae83-7b1b-49f5-8b6e-cb505ceb37ed-GRAPH_ID:0-PID:10-HOST:server-storage-pool-1-0-0-PC_NAME:storage-pool-1-client-0-RECON_NO:-0, error-xlator: storage-pool-1-quota 
[2021-06-15 14:01:41.181639 +0000] I [MSGID: 115060] [server-rpc-fops.c:932:_gf_server_log_setxattr_failure] 0-storage-pool-1-server: 11519886: SETXATTR /subvol/aa/00/pvc-32448cd0-cd12-404a-8a2c-674d03f4c0e4 (f16bc78b-edf4-494e-b043-1a0642fb01e4) ==> trusted.gfs.squota.size, client: CTX_ID:90b5ae83-7b1b-49f5-8b6e-cb505ceb37ed-GRAPH_ID:0-PID:10-HOST:server-storage-pool-1-0-0-PC_NAME:storage-pool-1-client-0-RECON_NO:-0, error-xlator: storage-pool-1-quota 
[2021-06-15 14:01:41.181668 +0000] I [MSGID: 115060] [server-rpc-fops_v2.c:864:server4_setxattr_cbk] 0-storage-pool-1-server: SETXATTR info [{client=CTX_ID:90b5ae83-7b1b-49f5-8b6e-cb505ceb37ed-GRAPH_ID:0-PID:10-HOST:server-storage-pool-1-0-0-PC_NAME:storage-pool-1-client-0-RECON_NO:-0}, {error-xlator=storage-pool-1-quota}, {errno=1}, {error=Operation not permitted}]
```

`xattr` works on the underlying XFS filesystem, as on the server:
```
root@server-storage-pool-1-0-0:/# getfattr -R /bricks/storage-pool-1/data/brick/
getfattr: Removing leading '/' from absolute path names
# file: bricks/storage-pool-1/data/brick/
user.testattr

# file: bricks/storage-pool-1/data/brick//.glusterfs/00/00/00000000-0000-0000-0000-000000000001
user.testattr
```

I don't know what access pattern Prometheus may use on it's storage but I was unable to reproduce this phenomenon with simple `cat` and `rm`.

It's possible that using GlusterFS as a Prometheus storage backend is suboptimal or not advised or something. I would be happy to hear about it if that's the case. But this issue report is about the said strange behavior.

I'm really just evaluate Kadalu and GlusterFS so I'm not an expert in this subject and very well possible that I miss something in configuration or somewhere else.

What do you guys think about this issue?

Thank you!

**Comment by leelavg** [comment]
@benedekl 

Thanks for the report, stopped after going through below out of confusion 😕

> $ kubectl get pods -n kadalu -o wide

Are you sure that there are no more entries? Unless I'm mistaken `nodeplugin` should run on every node as a daemonset and not able to see that from above o/p.

Will update the comment after going through entire issue.

**Comment by amarts** [comment]
> What do you guys think about this issue?

Thanks for the report. This is surely some bug with simple-quota. Looks like the issue happened because of self-heal on a directory with quota limit set. Looks like while setting quota xattr there seems to be an issue.

One possible quick way to get rid of this is by removing `trusted.gfs.squota.limit` from the PVC dir on all storage devices (bricks).  Note that it will make the PV show all volume's data. But it should still allow other PVs to be created and storage work normally to Prometheus.

**Comment by benedekl** [comment]
@leelavg @amarts

Thanks for your replies. Yes, currently these are the only pods running as I have to use the master nodes as bricks. I'm not sure if `nodeplugin` need to run on the server nodes as well or not. The fact that every PV works well except the one used by Prometheus tells me it is not needed. On the masters there will be no pod consuming PVs provisioned by Kadalu.

A quick check in the Prometheus source code shows me that it probably uses `fallocate` on Linux.

I'm not sure about this `trusted.gfs.squota.limit`. I think it's an xattr but I can only see two `user.testattr` xattrs in the brick. Please check my original report for details.

**Comment by leelavg** [comment]
@benedekl 

> On the masters there will be no pod consuming PVs provisioned by Kadalu

I understood that it was because of taints and my comment served no purpose, so removed it.

Yes, `nodeplugin` is only needed whey there are pods consuming storage scheduled on that node 😃

**Comment by benedekl** [comment]
@leelavg

Thank you for confirming this for me!

**Comment by KyleSanderson** [comment]
This seems to be inode related for me, my incredibly basic music directory kicks something into gear and kills the pv. What's the fix?

**Comment by KyleSanderson** [comment]
@leelavg @aravindavk any update on this? Can I do anything more to help fix this bug? It's pretty devastating as it's blocking anyone from using this 😿

**Comment by amarts** [comment]
@KyleSanderson this is bad, and yes, it is possibly something to do with the inode context... One possible quick fix is as suggested in [comment](https://github.com/kadalu/kadalu/issues/577#issuecomment-861658425) above, remove the xattr on directory which sets the quota as 0, and do a kill of the server pods (which should restart server pods without xattr). 

Also when this happens, try to check for a statedump, get into server pod and send SIGUSR1 to `glusterfsd` process, that may give some hints.

**Comment by benedekl** [comment]
@amarts How is it possible that there is no such xattr on my directories and I'm still affected by this? The mentioned `trusted.gfs.squota.limit` has never been there, at least I didn't remove it by hand.
```
root@server-storage-pool-1-0-0:/# getfattr -R /bricks/
getfattr: Removing leading '/' from absolute path names
# file: bricks//storage-pool-1/data/brick
user.testattr

# file: bricks//storage-pool-1/data/brick/.glusterfs/00/00/00000000-0000-0000-0000-000000000001
user.testattr
```
```
root@server-storage-pool-1-1-0:/# getfattr -R /bricks/
getfattr: Removing leading '/' from absolute path names
# file: bricks//storage-pool-1/data/brick
user.testattr

# file: bricks//storage-pool-1/data/brick/.glusterfs/00/00/00000000-0000-0000-0000-000000000001
user.testattr
```
```
root@server-storage-pool-1-2-0:/# getfattr -R /bricks/
getfattr: Removing leading '/' from absolute path names
# file: bricks//storage-pool-1/data/brick
user.testattr

# file: bricks//storage-pool-1/data/brick/.glusterfs/00/00/00000000-0000-0000-0000-000000000001
user.testatt
```

The server pod logs this (and similar messages)  in every second:
```
[2021-06-30 10:07:26.267639 +0000] I [MSGID: 108026] [afr-self-heal-metadata.c:51:__afr_selfheal_metadata_do] 0-storage-pool-1-replica-0: performing metadata selfheal on e01b6ba2-efcb-4ba3-ac56-9fde6dd69da1 
[2021-06-30 10:07:26.270077 +0000] W [MSGID: 114031] [client-rpc-fops_v2.c:842:client4_0_setxattr_cbk] 0-storage-pool-1-client-0: remote operation failed. [{errno=1}, {error=Operation not permitted}] 
[2021-06-30 10:07:26.277466 +0000] W [MSGID: 114031] [client-rpc-fops_v2.c:842:client4_0_setxattr_cbk] 0-storage-pool-1-client-0: remote operation failed. [{errno=1}, {error=Operation not permitted}] 
[2021-06-30 10:07:26.279890 +0000] I [MSGID: 108026] [afr-self-heal-common.c:1732:afr_log_selfheal] 0-storage-pool-1-replica-0: Completed metadata selfheal on db9be85e-92e2-4b3f-964c-dcdf5283bfc3. sources=1 [2]  sinks= 
[2021-06-30 10:07:26.282809 +0000] I [MSGID: 108026] [afr-self-heal-metadata.c:51:__afr_selfheal_metadata_do] 0-storage-pool-1-replica-0: performing metadata selfheal on f16bc78b-edf4-494e-b043-1a0642fb01e4 
[2021-06-30 10:07:26.285124 +0000] W [MSGID: 114031] [client-rpc-fops_v2.c:842:client4_0_setxattr_cbk] 0-storage-pool-1-client-0: remote operation failed. [{errno=1}, {error=Operation not permitted}] 
[2021-06-30 10:07:26.287143 +0000] I [MSGID: 108026] [afr-self-heal-common.c:1732:afr_log_selfheal] 0-storage-pool-1-replica-0: Completed metadata selfheal on f16bc78b-edf4-494e-b043-1a0642fb01e4. sources=1 [2]  sinks= 
```
Sending `SIGUSR1` to `glusterfsd` shows nothing more in the logs.

**Comment by kondas** [comment]
Hello guys, i encountered the same "Quota exceeded" while evaluating kadalu. I can reproduce consistently with a disk benchmark pod on a kadalu backed PV. Issue persist using "path" method for storage, formatted to xfs and mounted manually.  trusted.gfs.squota.limit xattr is absent from the start.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-pv-claim
spec:
  storageClassName: kadalu
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: fbuchmeier/dbench:latest
        imagePullPolicy: Always
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-pv-claim
  backoffLimit: 4
```

**Comment by amarts** [comment]
Thanks for this reproducer. One question, is the storage replica1/2 or 3?

**Comment by kondas** [comment]
The storageservers logs are flooded with this message in my setup: 
```
[2021-07-05 18:53:53.338511 +0000] E [MSGID: 115067] [server-rpc-fops_v2.c:1325:server4_writev_cbk] 0-storage-pool-1-server: WRITE info [{frame=596776}, {WRITEV_fd_no=1}, {uuid_utoa=147122e2-2431-4c01-afd9-10afdcb04dbe}, {client=CTX_ID:f9c15436-4861-42d7-a232-bea9bb1f0c7d-GRAPH_ID:0-PID:38-HOST:kadalu-csi-nodeplugin-s2gf6-PC_NAME:storage-pool-1-client-0-RECON_NO:-1}, {error-xlator=storage-pool-1-quota}, {errno=122}, {error=Disk quota exceeded}]
```
@amarts  I created the storage like this, its replica1: 
```
kubectl kadalu storage-add storage-pool-1 --path k8s-3:/glusterfs  --path k8s-2:/glusterfs --pathk8s-1:/glusterfs
```

EDIT: The issue is the same using replica3

on the hosts there is a **cached LVM LV** formatted to XFS and mounted.

Previous setup was passing the "raw" LV-s to the storage pool, quota error also. 
```
  LV            VG      Attr       LSize  Pool                      Origin                Data%  Meta%  Move Log Cpy%Sync Convert
  gluster-brick vg_data Cwi-aoC--- <3.86t [gluster-brick-cachepool] [gluster-brick_corig] 7.36   15.98           0.00`
```

**Comment by amarts** [comment]
@kondas if you have cycles, can you check the latest `devel` tag (for specially server pods) and see if that makes any difference? I have added https://github.com/kadalu/glusterfs/pull/2 in the mix. Some issues should be resolved IMO with it. While we continue to test and fix issues, a validation on this would help us.

**Comment by kondas** [comment]
@amarts I've reinstalled kadalu with argument "--version=devel", and i can see operator and storage-server pods are on the devel tag. I still get the "Quota exceeded" error with dbench.

**Comment by KyleSanderson** [comment]
Any update on this devastating bug?

**Comment by amarts** [comment]
Latest `devel` tag has one more fix which should resolve some more issues in simple-quota.

I haven't able to test the fixes in k8s ecosystem yet. If the latest devel branch is tested, we can take a call on this.

**Comment by kondas** [comment]
@amarts Latest devel tag (16062ca660a2) still has the issue

**Comment by KyleSanderson** [comment]
Still having issues on this one with devel.

**Comment by amarts** [comment]
> Still having issues on this one with devel.

Sorry about delay in this. Taking more time than anticipated. Will keep the issue posted on progress.

**Comment by couloum** [comment]
Hi,

We encountered the same bug after upgrade on v0.8.3. I have another way to reproduce the issue:
- Create a pod integrating rsync, with a PVC attached
- Start a rsync transfer (download on the pod)
- Start again rsync transfer on same file
- The quota is increased at each rsync execution

Here are the log of this (I have changed rsync server's url and filename):
```
/tmp # ls -lh
total 0

/tmp # df -h .
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool      20.0G         0     20.0G   0% /tmp

/tmp # rsync --password-file /rsync.passwd username@server::file /tmp

/tmp # ls -lah
total 772223
drwxrwxrwx    2 root     root          26 Jul 22 08:05 .
drwxr-xr-x    1 root     root        4.0K Jul 22 08:03 ..
-rw-r--r--    1 root     root      754.1M Jul 22 08:05 file

/tmp # df -h .
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool      20.0G    754.4M     19.3G   4% /tmp

/tmp # rsync --password-file /rsync.passwd username@server::file /tmp

/tmp # ls -lah
total 772223
drwxrwxrwx    2 root     root          26 Jul 22 08:06 .
drwxr-xr-x    1 root     root        4.0K Jul 22 08:03 ..
-rw-r--r--    1 root     root      754.1M Jul 22 08:06 file

/tmp # df -h .
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool      20.0G      1.5G     18.5G   7% /tmp
```

As you can see in last `df` command, usage is twice the size it should be. It is increased by 754MB each time I run rsync.

**Comment by couloum** [comment]
Would it be possible to provide a detailed procedure on how to apply the workaround, from [this comment](https://github.com/kadalu/kadalu/issues/577#issuecomment-861658425)?

**Comment by amarts** [comment]
@couloum thanks for this report, in detail. Looks like this is happening due to a bug we identified in glusterfs codebase of kadalu's simple-quota. Made fixes which are available in devel branch now, 0.8.4 should have fix for it. Meantime, we are looking at providing a script in storage layer to recalibrate  based on their usage.

There seems to be one more issue which is taking time to fix, which is delaying 0.8.4 tagging. Will keep this issue posted.

**Comment by leelavg** [comment]
@amarts / @aravindavk 

Something's fundamentally broken in quota crawler and subsequent quota ops are failing if I'm not wrong.

I tested with below manifest:

``` yaml
# Storage 10Gi
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: replica1
spec:
  type: Replica1
  storage:
    - node: k3d-test-agent-0
      device: /dev/sdc

# PVC 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbench-pv-claim
spec:
  storageClassName: kadalu.replica1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dbench
spec:
  template:
    spec:
      containers:
      - name: dbench
        image: fbuchmeier/dbench:latest
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
        volumeMounts:
        - name: dbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: dbench-pv
        persistentVolumeClaim:
          claimName: dbench-pv-claim
  backoffLimit: 4
```

a. I can hit the same disk quota exceed warning, however below are my observations
1. I asked for a 1G vol but I was able to use ~3.6G of PVC before I hit the warning (server logs are filled with quota warning so unfortunately couldn't access disk initilization logs). We do have a lot of free inodes, no issues there.
```
# k exec -it server-replica1-0-0 -- bash
root@server-replica1-0-0:/# df -ih | grep -P 'data|File'
Filesystem          Inodes IUsed IFree IUse% Mounted on
/dev/sdc              5.0M   308  5.0M    1% /bricks/replica1/data
root@server-replica1-0-0:/# df -h | grep -P 'data|File'
Filesystem           Size  Used Avail Use% Mounted on
/dev/sdc              10G  3.6G  6.5G  36% /bricks/replica1/data
root@server-replica1-0-0:/# 
```

2. Quota crawler process isn't setting xattr (`glusterfs.quota.total-usage`) after PVC is carved and not sure why `size` attr is set to a negative value
```
# k exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- bash
root@kadalu-csi-provisioner-0:/# getfattr -d -e text -m. /mnt/replica1/subvol/50/5d/pvc-40429f46-d1d3-4fed-9b54-00fc2b948ba1/
getfattr: Removing leading '/' from absolute path names
# file: mnt/replica1/subvol/50/5d/pvc-40429f46-d1d3-4fed-9b54-00fc2b948ba1/
security.selinux="system_u:object_r:fusefs_t:s0"
trusted.gfs.squota.limit="1073741824"
trusted.gfs.squota.size="-2147483648"
trusted.glusterfs.mdata="\000\000\000\000\000\000\000\000\000\000\000\000`(x\000\000\000\000\000\000\000\000`'\000\000\000\000!\000\000\000\000\000`%\000\000\000\0003[Z"
trusted.glusterfs.namespace="true"
```

3. Does below has to do anything with quota (log is flooded with this warning)?
```
# k logs kadalu-csi-provisioner-0 -c kadalu-logging  | tail -n 2
[2021-07-26 03:55:49.622625 +0000] W [dict.c:1573:dict_get_with_ref] (-->/opt/lib/glusterfs/2021.06.21/xlator/performance/md-cache.so(+0x1007c) [0x7fe7f9aff07c] -->/opt/lib/libglusterfs.so.0(dict_get_iatt+0x41) [0x7fe7fe063071] -->/opt/lib/libglusterfs.so.0(dict_get_with_ref+0x61) [0x7fe7fe060c81] ) 0-dict: dict OR key (virt-gf-prestat) is NULL [Invalid argument]
[2021-07-26 03:55:54.659123 +0000] W [dict.c:1573:dict_get_with_ref] (-->/opt/lib/glusterfs/2021.06.21/xlator/performance/md-cache.so(+0x1007c) [0x7fe7f9aff07c] -->/opt/lib/libglusterfs.so.0(dict_get_iatt+0x41) [0x7fe7fe063071] -->/opt/lib/libglusterfs.so.0(dict_get_with_ref+0x61) [0x7fe7fe060c81] ) 0-dict: dict OR key (virt-gf-prestat) is NULL [Invalid argument]
```
4. Not sure why `getfattr` isn't accessible in `server` pod but I can see limit being set
```
# k exec -it server-replica1-0-0 -- bash
root@server-replica1-0-0:/# python
Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xattr
>>> xattr.get('/bricks/replica1/data/brick/subvol/50/5d/pvc-40429f46-d1d3-4fed-9b54-00fc2b948ba1', 'trusted.gfs.squota.limit')
b'1073741824'
>>> 
root@server-replica1-0-0:/# type getfattr
bash: type: getfattr: not found
```

b. Need to look:
1. Why usage is not being set on PVC subdir
2. Even if usage isn't getting updated why simple quota is allowing more than `limit`
3. Assuming, limit & usage having some issue, why we are hitting disk quota when we fill ~36% of volume but not entire volume
4. As per limit is concerned ig `SizeAccounting` is working fine, are we hitting any corner case?

Did I miss any observations which you are already aware of?

I'm not sure whether my observations are tied to my local cluster alone or not however they do match against above comments. So, ig it's reproducible with minikube as well.

**Comment by couloum** [comment]
Hi,

As this quota issue is very problematic, is there a workarround that we could apply?
I have only 2 options for now:
1) Backup data, destroy pvc, recreate it and restore data
2) Switch to local storage

Both workarrounds are not so great. I would prefer to temporarily disable quota.

Thanks

**Comment by leelavg** [comment]
hi @couloum,

As per my observation, I see no (easy) way out of this situation and we (at-least I) don't have a solid understanding on where things are going wrong.

I'm thinking to bisect commits using a binary search to find out the culprit commit using github CI however scripting it out might take some considerable amount of time.

@amarts will we be losing many functionalities if we switch gluster to `series_0` or at-least back-port important commits to `series_0` and make a build if we are sure kadalu commits aren't the culprit?

**Comment by amarts** [comment]
@leelavg thanks for tests.

@couloum @hunter86bg, @kondas and others... Here are the action plan on this issue.

1. Make a release of 0.8.4 with 1 major option - to disable simple quota check for fops. - ETA -2 days (ie, by end of 27th July, GMT)
2. Work on fixing the quota issue and solve it with definite timeline. - Aug 12th.
3. Provide an option to 'reset' quota based on the actual usage, and re-enable it back. 
4. After steps 2 & 3 are completed, make 0.8.5 release which should have any Quota related issues fixed. - Aug 16th.

Thanks for the reports and patience on waiting for the fix.

**Comment by amarts** [comment]
> trusted.gfs.squota.size="-2147483648"

This is a concern. I fixed an issue after the first reported issue post 0.8.3 where there is a check for less than 0 usage. Ideally the usage shouldn't get to negative. That is a red signal for sure.

> `df -h | grep -P 'data|File'`

We can't see the particular PVCs in `df -h` usage. They are just a directory, not mount points (specially on the provisioner pod). So, you need to apply `df -h $pvc_subdir` to see the limit being issued.

> About missing getfattr.

I guess `{g,s}etfattr` tools are not installed on server pods. Considering they are helpful for debug, and also some handy commands, looks like we need to install it.

**Comment by leelavg** [comment]
> you need to apply df -h $pvc_subdir to see the limit being issued.

Just realised this 😅. I did take o/p of that and the `fiotest` file itself in the PVC spanned ~3.5G. 

And the volume doesn't have any other PVC. So the total usage here is almost occupied by that single PVC.

**Comment by amarts** [comment]
Ok, some update on this thread.

1. As promised, we made a release with 'disable quota' option - https://github.com/kadalu/kadalu/releases/tag/0.8.4
2. With few fixes which went into to Quota code on glusterfs side for the release, looks like https://github.com/kadalu/glusterfs/commit/16f37030c2769b9625794ed108e5573981e3342e should fix the real issue. It escaped my testing because I was testing on happy conditions below 2GB PV volume size, and hence was not able to hit the bug. Please upgrade and see if it resolves the issue for you before disabling quota.
  - Note that, if your PV is already reporting quota limit exceeded error, then you may need to reset the quota, for which we are working on the script (which can be executed separately).
  - For now, only on new PVs you can see if the issues are fixed.

We are still keeping this thread open, and working on any remaining issues of quota, and keeping the target of Aug 16th for next release with all fixes, but believe most of it may be already fixed in 0.8.4 in any case.

**Comment by KyleSanderson** [comment]
@amarts you've forgotten to do a DockerHub release - there's no new tag.

**Comment by KyleSanderson** [comment]
Yeah - no one can install Kadalu right now because the new operator has been shipped + docs updated but there's (still) no valid image...

Can CI please be added. This is storage, if there's a ethernet nic bug the frames will get transmitted, if there's storage corruption you're losing all of your data - this is very important to get right.

**Comment by aravindavk** [comment]
@KyleSanderson It is available now. After creating tag, CI took some time to publish the images to dockerhub.

**Comment by leelavg** [comment]
all,

did a quick check, it looks good, we will work on providing a script to flip the xattrs correctly at the earliest.

expanding on what we are trying to do:

- we need to set `limit` and `size` on PVCs created in 0.8.3 correctly and the rest will be taken care

On 0.8.3:

```
root@kadalu-csi-provisioner-0:~# getfattr -d -e text -m. /mnt/replica1/subvol/50/5d/pvc-40429f46-d1d3-4fed-9b54-00fc2b948ba1
getfattr: Removing leading '/' from absolute path names
# file: mnt/replica1/subvol/50/5d/pvc-40429f46-d1d3-4fed-9b54-00fc2b948ba1
security.selinux="system_u:object_r:fusefs_t:s0"
trusted.gfs.squota.limit="1073741824"
trusted.gfs.squota.size="-2147483648"
trusted.glusterfs.mdata="\000\000\000\000\000\000\000\000\000\000\000\000`(x\000\000\000\000\000\000\000\000`'\000\000\000\000!\000\000\000\000\000`%\000\000\000\0003[Z"
trusted.glusterfs.namespace="true"

root@kadalu-csi-provisioner-0:~# du -chs /mnt/replica1/subvol/50/5d/pvc-40429f46-d1d3-4fed-9b54-00fc2b948ba1
3.5G    /mnt/replica1/subvol/50/5d/pvc-40429f46-d1d3-4fed-9b54-00fc2b948ba1
3.5G    total
```


After upgrade to 0.8.4:

```
root@kadalu-csi-provisioner-0:~# getfattr -d -e text -m. /mnt/replica1/subvol/d1/72/pvc-fe376fea-859e-4cb4-ad33-ed1b9ae75163
getfattr: Removing leading '/' from absolute path names
# file: mnt/replica1/subvol/d1/72/pvc-fe376fea-859e-4cb4-ad33-ed1b9ae75163
security.selinux="system_u:object_r:fusefs_t:s0"
trusted.gfs.squota.limit="1073741824"
trusted.gfs.squota.size="1073742336"
trusted.glusterfs.mdata="\000\000\000\000\000\000\000\000\000\000\000\000a\000F\000\000\000\000ڃ/\000\000\000\000a\000\000\000\000\000^5\000\000\000\000a\000ƴ\000\000\000\000)%"
trusted.glusterfs.namespace="true"

root@kadalu-csi-provisioner-0:~# du -chs /mnt/replica1/subvol/d1/72/pvc-fe376fea-859e-4cb4-ad33-ed1b9ae75163
985M    /mnt/replica1/subvol/d1/72/pvc-fe376fea-859e-4cb4-ad33-ed1b9ae75163
985M    total
root@kadalu-csi-provisioner-0:~# 
```

**Comment by aravindavk** [comment]
> we need to set limit and size on PVCs created in 0.8.3 correctly and the rest will be taken care

I think removing `trusted.gfs.squota.size` should be fine to make it work with 0.8.4? @amarts ^^

**Comment by amarts** [comment]
Steps to get it right:

1. remove `trusted.gfs.squota.size` xattr.
2. calculate `du -s -b $pvcdir` and set the value (value in bytes)  into `trusted.gfs.squota.size`
3. if storage pods are already running then one need to issue `setfattr -n glusterfs.quota.reset -v true $pvcdir`, so the process can reset the relevant fields while running.

**Comment by leelavg** [comment]
@aravindavk 

> I think removing `trusted.gfs.squota.size`

In my case `limit` didn't overflow because it's containable in `int32` but whoever has carved more PVC, they would see it as overflowed.

@amarts small info,

does `setfattr -n glusterfs.quota.reset -v true $pvcdir` resets both `limit` and `size` attrs? Will continue discussion in slack.

**Comment by couloum** [comment]
Hello,

We did the upgrade on our preview environment and it seems the issue **is still present** with our use-case.

I created a new pvc, and a test pod after the upgrade and performed my rsync commands:

```
# Already performed 3 rsync before this snippet

/data # df -h .
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool      15.0G      2.3G     12.7G  15% /data
/data # du -shc .
768.2M  .
768.2M  total

/data # rsync --password-file /rsync.passwd username@server::file /data

/data # df -h .
Filesystem                Size      Used Available Use% Mounted on
kadalu:storage-pool      15.0G      3.1G     11.9G  20% /data
/data # du -shc .
768.2M  .
768.2M  total
```

We need to try to deactivate quota now to see if it works as expected.

**Comment by leelavg** [comment]
hi @couloum 

it's a bit confusing to understand, can you provide o/p of below?

wanted to know whether you had reset the xattr or not as per https://github.com/kadalu/kadalu/issues/577#issuecomment-888012525

```
-> pvcs=($(kubectl exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- bash -c 'find /mnt/*/subvol/*/* -maxdepth 1 -mindepth 1 -type d'))
-> for pvc in ${pvcs[@]}; do pvc=$(echo $pvc | tr -d '[:space:]'); kubectl exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- bash -c "getfattr -d -e text -m. $pvc"; done;
```

**Comment by couloum** [comment]
Hi,

here are more information about my test.

First, my setup:

```
# kubectl -n kadalu get all -o wide

NAME                              READY   STATUS    RESTARTS   AGE     IP            NODE      NOMINATED NODE   READINESS GATES
pod/kadalu-csi-nodeplugin-ttz28   3/3     Running   0          4h17m   10.244.3.43   node03s   <none>           <none>
pod/kadalu-csi-nodeplugin-z2t6c   3/3     Running   0          4h18m   10.244.4.39   node02s   <none>           <none>
pod/kadalu-csi-nodeplugin-z6nf7   3/3     Running   0          4h19m   10.244.5.14   node01s   <none>           <none>
pod/kadalu-csi-provisioner-0      5/5     Running   0          4h19m   10.244.5.30   node01s   <none>           <none>
pod/operator-68d8bb8bb6-5rcz7     1/1     Running   0          4h20m   10.244.5.28   node01s   <none>           <none>
pod/server-storage-pool-0-0       1/1     Running   0          4h19m   10.244.5.15   node01s   <none>           <none>
pod/server-storage-pool-1-0       1/1     Running   0          4h19m   10.244.4.11   node02s   <none>           <none>
pod/server-storage-pool-2-0       1/1     Running   0          4h19m   10.244.3.15   node03s   <none>           <none>

NAME                   TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE    SELECTOR
service/storage-pool   ClusterIP   None         <none>        24007/TCP   323d   app.kubernetes.io/component=server,app.kubernetes.io/name=server,app.kubernetes.io/part-of=kadalu

NAME                                   DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE    CONTAINERS                                                   IMAGES                                                                                                               SELECTOR
daemonset.apps/kadalu-csi-nodeplugin   3         3         3       3            3           <none>          273d   csi-node-driver-registrar,kadalu-nodeplugin,kadalu-logging   docker.io/raspbernetes/csi-node-driver-registrar:2.0.1,docker.io/kadalu/kadalu-csi:0.8.4,docker.io/library/busybox   app.kubernetes.io/component=csi-driver,app.kubernetes.io/name=kadalu-csi-nodeplugin,app.kubernetes.io/part-of=kadalu

NAME                       READY   UP-TO-DATE   AVAILABLE   AGE    CONTAINERS        IMAGES                                   SELECTOR
deployment.apps/operator   1/1     1            1           323d   kadalu-operator   docker.io/kadalu/kadalu-operator:0.8.4   name=kadalu

NAME                                  DESIRED   CURRENT   READY   AGE     CONTAINERS        IMAGES                                   SELECTOR
replicaset.apps/operator-59d9898769   0         0         0       188d    kadalu-operator   docker.io/kadalu/kadalu-operator:0.7.6   name=kadalu,pod-template-hash=59d9898769
replicaset.apps/operator-5c8fdb544c   0         0         0       92d     kadalu-operator   docker.io/kadalu/kadalu-operator:0.7.7   name=kadalu,pod-template-hash=5c8fdb544c
replicaset.apps/operator-5fc6fbb867   0         0         0       92d     kadalu-operator   docker.io/kadalu/kadalu-operator:0.7.7   name=kadalu,pod-template-hash=5fc6fbb867
replicaset.apps/operator-68d8bb8bb6   1         1         1       4h20m   kadalu-operator   docker.io/kadalu/kadalu-operator:0.8.4   name=kadalu,pod-template-hash=68d8bb8bb6
replicaset.apps/operator-69467fc5d9   0         0         0       264d    kadalu-operator   docker.io/kadalu/kadalu-operator:0.7.1   name=kadalu,pod-template-hash=69467fc5d9
replicaset.apps/operator-69476b66b4   0         0         0       56d     kadalu-operator   docker.io/kadalu/kadalu-operator:0.8.2   name=kadalu,pod-template-hash=69476b66b4
replicaset.apps/operator-75b79d8f68   0         0         0       12d     kadalu-operator   docker.io/kadalu/kadalu-operator:0.8.3   name=kadalu,pod-template-hash=75b79d8f68
replicaset.apps/operator-779bfbc75    0         0         0       92d     kadalu-operator   docker.io/kadalu/kadalu-operator:0.7.7   name=kadalu,pod-template-hash=779bfbc75
replicaset.apps/operator-78b6897f4d   0         0         0       92d     kadalu-operator   docker.io/kadalu/kadalu-operator:0.7.7   name=kadalu,pod-template-hash=78b6897f4d
replicaset.apps/operator-79dbd46589   0         0         0       92d     kadalu-operator   docker.io/kadalu/kadalu-operator:0.7.7   name=kadalu,pod-template-hash=79dbd46589
replicaset.apps/operator-7dfd7bc877   0         0         0       92d     kadalu-operator   docker.io/kadalu/kadalu-operator:0.7.7   name=kadalu,pod-template-hash=7dfd7bc877

NAME                                      READY   AGE    CONTAINERS                                                                   IMAGES
statefulset.apps/kadalu-csi-provisioner   1/1     273d   csi-provisioner,csi-attacher,kadalu-provisioner,kadalu-logging,csi-resizer   docker.io/raspbernetes/csi-external-provisioner:2.0.2,docker.io/raspbernetes/csi-external-attacher:3.0.0,docker.io/kadalu/kadalu-csi:0.8.4,docker.io/library/busybox,docker.io/raspbernetes/csi-external-resizer:1.0.0
statefulset.apps/server-storage-pool-0    1/1     323d   server                                                                       docker.io/kadalu/kadalu-server:0.8.4
statefulset.apps/server-storage-pool-1    1/1     323d   server                                                                       docker.io/kadalu/kadalu-server:0.8.4
statefulset.apps/server-storage-pool-2    1/1     323d   server                                                                       docker.io/kadalu/kadalu-server:0.8.4
```

Everything is running in `v0.8.4`.

Then, my manifest `testapp.yaml`:

```
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: testapp
  name: testapp-secrets
type: Opaque
data:
  RSYNC_PASSWORD: ********
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: testapp
  name: testapp-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: kadalu.replica3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testapp
  name: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: testapp-secrets
        image: nginx
        imagePullPolicy: IfNotPresent
        name: testapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: testapp-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: testapp-data
        persistentVolumeClaim:
          claimName: testapp-pvc
```

I start from a fresh namespace:

```
# kubectl -n test get all
No resources found in test namespace.
```

Then I apply the manifest:

```
# kubectl -n test apply -f testapp.yaml
secret/testapp-secrets created
persistentvolumeclaim/testapp-pvc created
deployment.apps/testapp created
```

Finally, the test:
```
# kubectl -n test exec -ti testapp-594ffff559-j6jwl -- bash
root@testapp-594ffff559-j6jwl:/# cd /data/
root@testapp-594ffff559-j6jwl:/data# df -h .
Filesystem           Size  Used Avail Use% Mounted on
kadalu:storage-pool   16G     0   16G   0% /data
root@testapp-594ffff559-j6jwl:/data# ls -lh
total 0
root@testapp-594ffff559-j6jwl:/data# apt update && apt install rsync
...
root@testapp-594ffff559-j6jwl:/data# echo $RSYNC_PASSWORD > /testapp.passwd ; chmod 400 /testapp.passwd

root@testapp-594ffff559-j6jwl:/data# rsync --progress -v --password-file /testapp.passwd ******@rsync.********::********** /data
**********
    794,427,838 100%    4.99MB/s    0:02:31 (xfr#1, to-chk=0/1)

sent 47 bytes  received 794,621,885 bytes  5,210,635.62 bytes/sec
total size is 794,427,838  speedup is 1.00
root@testapp-594ffff559-j6jwl:/data# du -shc .
758M    .
758M    total
root@testapp-594ffff559-j6jwl:/data# df -h .
Filesystem           Size  Used Avail Use% Mounted on
kadalu:storage-pool   16G  758M   15G   5% /data

root@testapp-594ffff559-j6jwl:/data# rsync --progress -v --password-file /testapp.passwd ******@rsync.********::********** /data
**********
    794,427,838 100%    5.05MB/s    0:02:29 (xfr#1, to-chk=0/1)

sent 197,371 bytes  received 112,851 bytes  2,007.91 bytes/sec
total size is 794,427,838  speedup is 2,560.84

root@testapp-594ffff559-j6jwl:/data# du -shc .
758M    .
758M    total
root@testapp-594ffff559-j6jwl:/data# df -h .
Filesystem           Size  Used Avail Use% Mounted on
kadalu:storage-pool   16G  1.5G   14G  10% /data
```

I am able to reproduce the issue without rsync:
```
root@testapp-594ffff559-28sx2:/data# df -h .
Filesystem           Size  Used Avail Use% Mounted on
kadalu:storage-pool   16G     0   16G   0% /data
root@testapp-594ffff559-28sx2:/data# du -shc .
0       .
0       total

root@testapp-594ffff559-28sx2:/data# dd if=/dev/urandom of=testfile bs=1M count=100

root@testapp-594ffff559-28sx2:/data# du -shc .
100M    .
100M    total
root@testapp-594ffff559-28sx2:/data# df -h .
Filesystem           Size  Used Avail Use% Mounted on
kadalu:storage-pool   16G  100M   15G   1% /data

root@testapp-594ffff559-28sx2:/data# cp testfile testfile2
root@testapp-594ffff559-28sx2:/data# du -shc .
200M    .
200M    total
root@testapp-594ffff559-28sx2:/data# df -h .
Filesystem           Size  Used Avail Use% Mounted on
kadalu:storage-pool   16G  200M   15G   2% /data

root@testapp-594ffff559-28sx2:/data# mv testfile2 testfile

root@testapp-594ffff559-28sx2:/data# du -shc .
100M    .
100M    total
root@testapp-594ffff559-28sx2:/data# df -h .
Filesystem           Size  Used Avail Use% Mounted on
kadalu:storage-pool   16G  200M   15G   2% /data

# Here, df should report 100M
```

Here is the result of commands you asked for:
```
# kubectl -n test get pvc
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
testapp-pvc   Bound    pvc-f6348553-4a65-457a-bb6d-14a203911c69   15Gi       RWX            kadalu.replica3   5m36s

# kubectl -n kadalu exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- bash -c 'find /mnt/*/subvol/*/* -maxdepth 1 -mindepth 1 -type d' | grep pvc-f6348553-4a65-457a-bb6d-14a203911c69
/mnt/storage-pool/subvol/c1/4a/pvc-f6348553-4a65-457a-bb6d-14a203911c69

# kubectl -n kadalu exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- bash -c "getfattr -d -e text -m. /mnt/storage-pool/subvol/c1/4a/pvc-f6348553-4a65-457a-bb6d-14a203911c69"
getfattr: Removing leading '/' from absolute path names
# file: mnt/storage-pool/subvol/c1/4a/pvc-f6348553-4a65-457a-bb6d-14a203911c69
trusted.gfs.squota.limit="16106127360"
trusted.gfs.squota.size="209716224"
trusted.glusterfs.mdata="\000\000\000\000\000\000\000\000\000\000\000\000aL\000\000\000\000+^\000\000\000\000aL\000\000\000\000+^\000\000\000\000aL2\000\000\000\000w?y"
trusted.glusterfs.namespace="true"
```

**Comment by amarts** [comment]
You have a file of 100MB, you copy it, it should be 200MB right? What am I missing here that you are expecting it to be 100MB?

**Comment by leelavg** [comment]
@couloum thanks, this is a very good reference. 

If I'm not wrong (sry I'm on mobile), after `cp` you performed `rm` on one of testfile{,2} and `du` showing `100M` whereas `df` is stuck at `200M` (or)

You didn't perform any `rm` but `du` is showing `100M` and `df` correctly reporting `200M`

Regarding xattrs, they are getting updated correctly and when I take xattr (`size`) on pvc dir as a source of truth `du` is incorrect but `df` is correct 

Am i missing anything here?

**Comment by couloum** [comment]
> 

> You have a file of 100MB, you copy it, it should be 200MB right? What am I missing here that you are expecting it to be 100MB?

Sorry, missed one important line in my report:

```
# This is done, juste after `cp` command
root@testapp-594ffff559-28sx2:/data# mv testfile2 testfile
```

I edited the original post to have the correct version.

Basically:
- Create a 100MB file. `df` reports 100MB usage.
- Copy the file. `df` reports 200MB usage.
- Move the copy to the original file (this delete the original file). `df` still reports 200MB usage.

Again, sorry for the confusion.

**Comment by leelavg** [comment]
Ack,

In that case can you do a `ls -lR` on `pvc` dir from `provisioner`?

Generally, it'd be a good ides to continue this discussion on slack if possible.

**Comment by couloum** [comment]
I disabled quota check on my pvc. I confirm that it works: I can create files, even if the volume reports 100% usage:

```
# kubectl -n kadalu exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- bash -c "setfattr -n glusterfs.quota.disable-check -v 1 /mnt/storage-pool/subvol/66/b4/pvc-3842ad3e-d0ea-4e7b-9797-b2266377eded"

# kubectl -n test exec -ti testapp-594ffff559-j4hrh -- bash
root@testapp-594ffff559-j4hrh:/# cd /data

root@testapp-594ffff559-j4hrh:/data# df -h .
kadalu:storage-pool      1.1G  1.1G     0 100% /data

root@testapp-594ffff559-j4hrh:/data# du -shc .
1.3G    .
1.3G    total

root@testapp-594ffff559-j4hrh:/data# ls -lh
total 1.3G
-rw-r--r-- 1 root root 100M Jul 28 12:48 testfile
-rw-r--r-- 1 root root 100M Jul 28 12:49 testfile.1
-rw-r--r-- 1 root root 100M Jul 28 12:55 testfile.10
-rw-r--r-- 1 root root 100M Jul 28 12:56 testfile.11
-rw-r--r-- 1 root root 100M Jul 28 12:56 testfile.12
-rw-r--r-- 1 root root 100M Jul 28 12:49 testfile.2
-rw-r--r-- 1 root root 100M Jul 28 12:50 testfile.3
-rw-r--r-- 1 root root 100M Jul 28 12:50 testfile.4
-rw-r--r-- 1 root root 100M Jul 28 12:50 testfile.5
-rw-r--r-- 1 root root 100M Jul 28 12:51 testfile.6
-rw-r--r-- 1 root root 100M Jul 28 12:51 testfile.7
-rw-r--r-- 1 root root 100M Jul 28 12:51 testfile.8
-rw-r--r-- 1 root root 100M Jul 28 12:52 testfile.9

root@testapp-594ffff559-j4hrh:/data# cp testfile testfile.13

root@testapp-594ffff559-j4hrh:/data# du -shc .
1.4G    .
1.4G    total

root@testapp-594ffff559-j4hrh:/data# ls -lh
total 1.4G
-rw-r--r-- 1 root root 100M Jul 28 12:48 testfile
-rw-r--r-- 1 root root 100M Jul 28 12:49 testfile.1
-rw-r--r-- 1 root root 100M Jul 28 12:55 testfile.10
-rw-r--r-- 1 root root 100M Jul 28 12:56 testfile.11
-rw-r--r-- 1 root root 100M Jul 28 12:56 testfile.12
-rw-r--r-- 1 root root 100M Jul 28 13:04 testfile.13
-rw-r--r-- 1 root root 100M Jul 28 12:49 testfile.2
-rw-r--r-- 1 root root 100M Jul 28 12:50 testfile.3
-rw-r--r-- 1 root root 100M Jul 28 12:50 testfile.4
-rw-r--r-- 1 root root 100M Jul 28 12:50 testfile.5
-rw-r--r-- 1 root root 100M Jul 28 12:51 testfile.6
-rw-r--r-- 1 root root 100M Jul 28 12:51 testfile.7
-rw-r--r-- 1 root root 100M Jul 28 12:51 testfile.8
-rw-r--r-- 1 root root 100M Jul 28 12:52 testfile.9

root@testapp-594ffff559-j4hrh:/data# df -h .
Filesystem           Size  Used Avail Use% Mounted on
kadalu:storage-pool  1.1G  1.1G     0 100% /data
```

If I reenable quota check, I cannot write anymore on pvc (expected behavior):
```
# kubectl -n kadalu exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- bash -c "setfattr -n glusterfs.quota.disable-check -v 0 /mnt/storage-pool/subvol/66/b4/pvc-3842ad3e-d0ea-4e7b-9797-b2266377eded"

# kubectl -n test exec -ti testapp-594ffff559-j4hrh -- bash
root@testapp-594ffff559-j4hrh:/# cd /data/
root@testapp-594ffff559-j4hrh:/data# cp testfile testfile.14
cp: cannot create regular file 'testfile.14': Disk quota exceeded
```

At least `v0.8.4` provide the workarround we expected untill a fix is found for quota calculation.

Thank for this release!

**Comment by digidvb** [comment]
@leelavg @couloum 

Thank you for your work. I can confirm that @couloum 's `mv` method does leak storage space.

After `mv` I even removed all the files from the PV. `du` shows 0, `ls` shows no files in the pod and in the provisioner as well, but `df` still shows used space.

I've freshly rebuilt the full storage from scratch with 0.8.4 images on wiped block devices.

**Comment by amarts** [comment]
Thanks guys. Hint on `mv` is what I had missed earlier. Identified the issue, fix should be available soon.

**Comment by digidvb** [comment]
Hi,

So, what is the possible solution to fix the previously miscalculated quota? I've tried the method with updating the `trusted.gfs.squota.size` and then setting `glusterfs.quota.reset` to `true`, but nothing happens. I've tried it with stopped, running pods, restarting server, provisioner, nodeplugin pods, but nothing helps.

I use this script to update the attrs:
``` shell
#!/bin/bash

set -eu

PROVISIONER="kubectl exec -n kadalu -it kadalu-csi-provisioner-0 -c kadalu-provisioner --"

PVCS=($(${PROVISIONER} bash -c 'find /mnt/*/subvol/*/* -maxdepth 1 -mindepth 1 -type d' | tr '[:space:]' ' '))

for PVC in ${PVCS[@]}; do
  printf "${PVC}\x1b[K\n"
  SIZE=$(${PROVISIONER} bash -c "du -s -b ${PVC}" | awk '{print $1}')
  printf "\x1b[1A${PVC} -> ${SIZE} bytes ...\n"
  ${PROVISIONER} bash -c "setfattr -n trusted.gfs.squota.size -v ${SIZE} ${PVC}"
  ${PROVISIONER} bash -c "setfattr -n glusterfs.quota.reset -v true ${PVC}"
  printf "\x1b[1A${PVC} -> ${SIZE} bytes ... OK\n"
done
```
After running it the size is updated in the attr. But `df` still shows the miscalculated value and after writing a file to the storage the `trusted.gfs.squota.size` attr updated back to the wrong value.

**Comment by leelavg** [comment]
@digidvb 

- Afaik, the `mv` fix will land up in next v0.8.5.
- If you've test setup, you can give a try deploying manifest (operator & csi-nodepugin) from `devel` branch.

**Comment by leelavg** [comment]
I think I know why the issue is happening (atleast some of it)

Interlude (just one-liners): `du` vs `df` and `simple-quota`
1. `df` respects fs superblocks and calculates the usage (~faster)
2. `du` doesn't care resepct info provided by fs but actually traverses each file and calculates the size/usage (~slower)
3. After a reset simple-quota trusts o/p from `df` (as stated below) to set `trusted.gfs.squota.size`, unless we take account of all fops correctly (mk*, unlink*) etc, `df` is skewed from truth
https://github.com/kadalu/kadalu/blob/61589acec98c1b2e91c0cf4fd77473dc8c2e5987/csi/quota-crawler.sh#L20-L26
4. simple-quota in regular intervals gets data from `statfs` to set `trusted.gfs.squota.size` but ig `df` also uses `statfs` so that explains https://github.com/kadalu/kadalu/issues/577#issuecomment-893336135

Possible fixes:
1. When `du` returns `0` usage or every 10 min (lesser intervals might degrade performance) we make simple-quota trust `du` rather than `df`, may not be bullet proof
2. Revisit simple-quota to grind out more errors around all fops (which I'm not however how this has to happen)

@amarts I just stated my observations and at the same time most of glusterfs (or) simple-quota internals is a black box to me, please disregard if it's not helpful

**Comment by couloum** [comment]
Hello,

I saw version `0.8.5` was just released. Does it contains the fix for quota miscalculation?

Thank you

**Comment by amarts** [comment]
> I saw version 0.8.5 was just released. Does it contains the fix for quota miscalculation?

All issues related to a fresh PV quota calculation are resolved in 0.8.5. The issue of miscalculated quota in the existing PV still remains. The scripts to update that scenario is not handled.

**Comment by couloum** [comment]
Thank you for the information. Is there a command that we could use to update the quota on existing PV? We could use `du` to get current usage and set it for each PV.

**Comment by amarts** [comment]
#650 is created to track the migration/fixing of wrongly calculated quotas.

This bugs in simple-quota which were genuine are now fixed, and are included in 0.8.5 and 0.8.6 releases.

**Comment by Creazy-MR** [comment]
Hi！
I'm having the same problem here, the quota capacity keeps growing and exceeding the limit, when in reality I'm not using that much. Can you please describe the reason for this phenomenon? Is it a gluster problem and how does the fix fix it.

ome details would be appreciated!  @amarts 

thanks！
